version: '3'

services:
    db:
        image: postgres:14
        restart: always
        environment:
            - POSTGRES_DB=scalerz
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '5432:5432'
        volumes:
            - pgdata:/var/lib/postgresql/data

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

volumes:
    pgdata:
        driver: local
