version: '3'

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8081:8081'
        depends_on:
            - db
        environment:
            - ENV=local
            - POSTGRES_DB=scalerz
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
    db:
        image: postgres:14
        restart: always
        environment:
            - POSTGRES_DB=scalerz
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '5432:5432'
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./src/db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

volumes:
    pgdata:
        driver: local
